name: Selenium Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install undetected-chromedriver

      - name: Run Selenium test and take screenshot
        run: python test/CardMarketSearch.py

      - name: Upload Screenshot as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: screenshot
          path: screenshot.png
